<a href="https://colab.research.google.com/github/isishdzmr99-collab/week2_pandas/blob/main/Pandas_Plotly_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Public Policy — Session 2 Workbook

**Data Manipulation with pandas + Interactive Charts with Plotly Express**

## Lesson 1: Warm‑Up — Tiny DataFrame

In [2]:
import pandas as pd

toys = {
    'country': ['A', 'B', 'C'],
    'year': [2005, 2006, 2007],
    'arrivals': [10, 0, 5]
}

toy_df = pd.DataFrame(toys)
toy_df

  country  year  arrivals
0       A  2005        10
1       B  2006         0
2       C  2007         5

🐻 PANDA time

In [18]:
import pandas as pd

In [19]:
toys_01 = {
    'country' : ['D', 'F', 'G'],
    'year': ['200', '2009', '2010'],
    'arrivals': [10, 0, 5]

}

In [20]:
toy_df = pd.DataFrame(toys_01)

In [23]:
import pandas as pd

toys_01 = {
    'country' : ['D', 'F', 'G'],
    'year': ['200', '2009', '2010'],
    'arrivals': [10, 0, 5]

}

toy_df = pd.DataFrame(toys_01)
toy_df

  country  year  arrivals
0       D   200        10
1       F  2009         0
2       G  2010         5

**Try it**
- Show only the `country` and `arrivals` columns.
- Filter rows where `arrivals` > 0.
- Compute `pct_total` = arrivals / total * 100.

In [15]:
# Your code here
# toy_df[['country', 'arrivals']]
# toy_df[toy_df['arrivals'] > 0]
# toy_df['pct_total'] = toy_df['arrivals'] / toy_df['arrivals'].sum() * 100
# toy_df

## Lesson 2: Load the Refugee Arrivals Dataset

**Data citation**
- U.S. refugee arrivals (2005–2015), compiled from the Refugee Processing Center (via Jeremy Singer‑Vine).

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/GC-DRI/DRI24/main/uploads/pandas/refugee-arrivals-by-destination.csv'
refugee_df = pd.read_csv(url)
len(refugee_df), refugee_df.head(3)

(121245,
    year       origin dest_state dest_city  arrivals
 0  2005  Afghanistan    Alabama    Mobile         0
 1  2006  Afghanistan    Alabama    Mobile         0
 2  2007  Afghanistan    Alabama    Mobile         0)

In [28]:
import pandas as pd
url = 'https://raw.githubusercontent.com/GC-DRI/DRI24/main/uploads/pandas/refugee-arrivals-by-destination.csv'

In [29]:
refugee_df = pd.read_csv(url)

In [31]:
refugee_df

        year       origin dest_state  dest_city  arrivals
0       2005  Afghanistan    Alabama     Mobile         0
1       2006  Afghanistan    Alabama     Mobile         0
2       2007  Afghanistan    Alabama     Mobile         0
3       2008  Afghanistan    Alabama     Mobile         0
4       2009  Afghanistan    Alabama     Mobile         5
...      ...          ...        ...        ...       ...
121240  2011      Vietnam  Wisconsin  Milwaukee         0
121241  2012      Vietnam  Wisconsin  Milwaukee         4
121242  2013      Vietnam  Wisconsin  Milwaukee         2
121243  2014      Vietnam  Wisconsin  Milwaukee         0
121244  2015      Vietnam  Wisconsin  Milwaukee         0

[121245 rows x 5 columns]

In [32]:
refugee_df.head(20)

    year       origin dest_state dest_city  arrivals
0   2005  Afghanistan    Alabama    Mobile         0
1   2006  Afghanistan    Alabama    Mobile         0
2   2007  Afghanistan    Alabama    Mobile         0
3   2008  Afghanistan    Alabama    Mobile         0
4   2009  Afghanistan    Alabama    Mobile         5
5   2010  Afghanistan    Alabama    Mobile         8
6   2011  Afghanistan    Alabama    Mobile         5
7   2012  Afghanistan    Alabama    Mobile         7
8   2013  Afghanistan    Alabama    Mobile         9
9   2014  Afghanistan    Alabama    Mobile         1
10  2015  Afghanistan    Alabama    Mobile         0
11  2005        Burma    Alabama    Auburn         0
12  2006        Burma    Alabama    Auburn         0
13  2007        Burma    Alabama    Auburn         0
14  2008        Burma    Alabama    Auburn         0
15  2009        Burma    Alabama    Auburn         0
16  2010        Burma    Alabama    Auburn         0
17  2007        Burma    Alabama    Auburn         0
18  2008        Burma    Alabama    Auburn         0
19  2009        Burma    Alabama    Auburn         0

In [33]:
refugee_df.tail(20)

        year   origin dest_state  dest_city  arrivals
121225  2007  Vietnam  Wisconsin    Madison         0
121226  2008  Vietnam  Wisconsin    Madison         0
121227  2009  Vietnam  Wisconsin    Madison         0
121228  2010  Vietnam  Wisconsin    Madison         0
121229  2011  Vietnam  Wisconsin    Madison         0
121230  2012  Vietnam  Wisconsin    Madison         4
121231  2013  Vietnam  Wisconsin    Madison         0
121232  2014  Vietnam  Wisconsin    Madison         1
121233  2015  Vietnam  Wisconsin    Madison         0
121234  2005  Vietnam  Wisconsin  Milwaukee         0
121235  2006  Vietnam  Wisconsin  Milwaukee         5
121236  2007  Vietnam  Wisconsin  Milwaukee        18
121237  2008  Vietnam  Wisconsin  Milwaukee        12
121238  2009  Vietnam  Wisconsin  Milwaukee         4
121239  2010  Vietnam  Wisconsin  Milwaukee         7
121240  2011  Vietnam  Wisconsin  Milwaukee         0
121241  2012  Vietnam  Wisconsin  Milwaukee         4
121242  2013  Vietnam  Wisconsin  Milwaukee         2
121243  2014  Vietnam  Wisconsin  Milwaukee         0
121244  2015  Vietnam  Wisconsin  Milwaukee         0

In [34]:
refugee_df[300:400]

     year   origin dest_state    dest_city  arrivals
300  2005     Iraq    Alabama        Foley         0
301  2006     Iraq    Alabama        Foley         0
302  2007     Iraq    Alabama        Foley         0
303  2008     Iraq    Alabama        Foley         0
304  2009     Iraq    Alabama        Foley         0
..    ...      ...        ...          ...       ...
395  2012  Liberia    Alabama   Montgomery         0
396  2013  Liberia    Alabama   Montgomery         0
397  2014  Liberia    Alabama   Montgomery         0
398  2015  Liberia    Alabama   Montgomery         0
399  2005  Liberia    Alabama  Phenix City         0

[100 rows x 5 columns]

### Quick exploration

In [35]:
refugee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121245 entries, 0 to 121244
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        121245 non-null  int64
 1   origin      121245 non-null  object
 2   dest_state  121245 non-null  object
 3   dest_city   121245 non-null  object
 4   arrivals    121245 non-null  int64
dtypes: int64(2), object(3)
memory usage: 4.6+ MB

In [40]:
refugee_df.sample(10)

        year       origin  dest_state      dest_city  arrivals
62702   2015         Laos   Minnesota    Minneapolis         0
36680   2008         Iran    Illinois  Franklin Park         0
18978   2005   Bangladesh    Colorado         Denver         0
104984  2013      Liberia       Texas        Garland         0
34620   2005     Ethiopia       Idaho     Twin Falls         0
100221  2013  Afghanistan       Texas       Richmond         0
51207   2015      Vietnam    Maryland      Baltimore         0
80519   2012   Uzbekistan    New York       Brooklyn         0
10678   2010         Iran  California    Yorba Linda         7
86898   2011         Iraq        Ohio    Mount Perry         0

❗ 🐻 if you use SAMPLE it is going to be random

**Try it**
- Show the last 7 rows.
- Show the first 10 unique origins.

In [ ]:
# refugee_df.tail(7)
# refugee_df['origin'].unique()[:10]

## Lesson 3: Cleaning Basics

### Data types
Keep `year` as an integer for grouping. Add `year_dt` for date operations if needed.

In [41]:
refugee_df['year_dt'] = pd.to_datetime(refugee_df['year'], format='%Y')
refugee_df.dtypes

year                   int64
origin                object
dest_state            object
dest_city             object
arrivals               int64
year_dt       datetime64[ns]
dtype: object

In [44]:
refugee_df.dtypes

year                   int64
origin                object
dest_state            object
dest_city             object
arrivals               int64
year_dt       datetime64[ns]
dtype: object

❗ ❗ ❗ ❗❗ ❗ ❗ ❗❗ ❗ ❗ ❗❗ ❗ ❗ ❗❗ ❗ ❗ ❗❗ ❗ ❗ ❗❗ ❗ ❗ ❗❗ ❗ ❗ ❗

In [100]:
refugee_df ['year_dt'] = pd.to_datetime(refugee_df ['year'], format= '%Y')

COMMENT needs [] ''

### Duplicates

In [54]:
refugee_df[refugee_df.duplicated(keep=False)].head(10)

     year origin dest_state     dest_city  arrivals    year_dt
13   2007  Burma    Alabama        Auburn         0 2007-01-01
14   2008  Burma    Alabama        Auburn         0 2008-01-01
15   2009  Burma    Alabama        Auburn         0 2009-01-01
16   2010  Burma    Alabama        Auburn         0 2010-01-01
17   2007  Burma    Alabama        Auburn         0 2007-01-01
18   2008  Burma    Alabama        Auburn         0 2008-01-01
19   2009  Burma    Alabama        Auburn         0 2009-01-01
20   2010  Burma    Alabama        Auburn         0 2010-01-01
155  2013   Cuba    Alabama  Russellville         0 2013-01-01
156  2014   Cuba    Alabama  Russellville         0 2014-01-01

In [55]:
refugee_df[refugee_df.duplicated(keep=False)]

     year origin dest_state     dest_city  arrivals    year_dt
13   2007  Burma    Alabama        Auburn         0 2007-01-01
14   2008  Burma    Alabama        Auburn         0 2008-01-01
15   2009  Burma    Alabama        Auburn         0 2009-01-01
16   2010  Burma    Alabama        Auburn         0 2010-01-01
17   2007  Burma    Alabama        Auburn         0 2007-01-01
18   2008  Burma    Alabama        Auburn         0 2008-01-01
19   2009  Burma    Alabama        Auburn         0 2009-01-01
20   2010  Burma    Alabama        Auburn         0 2010-01-01
155  2013   Cuba    Alabama  Russellville         0 2013-01-01
156  2014   Cuba    Alabama  Russellville         0 2014-01-01
157  2015   Cuba    Alabama  Russellville         0 2015-01-01
158  2005   Cuba    Alabama      Theodore         0 2005-01-01
159  2006   Cuba    Alabama      Theodore         0 2006-01-01
160  2013   Cuba    Alabama  Russellville         0 2013-01-01
161  2014   Cuba    Alabama  Russellville         0 2014-01-01
162  2015   Cuba    Alabama  Russellville         0 2015-01-01
163  2005   Cuba    Alabama      Theodore         0 2005-01-01
164  2006   Cuba    Alabama      Theodore         0 2006-01-01
236  2012   Iran    Alabama        Mobile         1 2012-01-01
237  2013   Iran    Alabama        Mobile         6 2013-01-01
238  2014   Iran    Alabama        Mobile         3 2014-01-01
239  2015   Iran    Alabama        Mobile         5 2015-01-01
240  2005   Iran    Alabama        Pelham         0 2005-01-01
247  2012   Iran    Alabama        Mobile         1 2012-01-01
248  2013   Iran    Alabama        Mobile         6 2013-01-01
249  2014   Iran    Alabama        Mobile         3 2014-01-01
250  2015   Iran    Alabama        Mobile         5 2015-01-01
251  2005   Iran    Alabama        Pelham         0 2005-01-01

from matplotlib import pyplot as plt
_df_0['year'].plot(kind='hist', bins=20, title='year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['arrivals'].plot(kind='hist', bins=20, title='arrivals')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('origin').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('dest_city').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='year', y='arrivals', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year_dt']
  ys = series['arrivals']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('year_dt', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('origin')):
  _plot_series(series, series_name, i)
  fig.legend(title='origin', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year_dt')
_ = plt.ylabel('arrivals')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year_dt']
  ys = series['arrivals']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('year_dt', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('dest_city')):
  _plot_series(series, series_name, i)
  fig.legend(title='dest_city', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year_dt')
_ = plt.ylabel('arrivals')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['year_dt']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'year_dt'}, axis=1)
              .sort_values('year_dt', ascending=True))
  xs = counted['year_dt']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('year_dt', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('origin')):
  _plot_series(series, series_name, i)
  fig.legend(title='origin', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year_dt')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['year_dt']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'year_dt'}, axis=1)
              .sort_values('year_dt', ascending=True))
  xs = counted['year_dt']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('year_dt', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('dest_city')):
  _plot_series(series, series_name, i)
  fig.legend(title='dest_city', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year_dt')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_9['year'].plot(kind='line', figsize=(8, 4), title='year')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['arrivals'].plot(kind='line', figsize=(8, 4), title='arrivals')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['dest_city'].value_counts()
    for x_label, grp in _df_11.groupby('origin')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('origin')
_ = plt.ylabel('dest_city')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_12['origin'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_12, x='year', y='origin', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['dest_city'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='year', y='dest_city', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['origin'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='arrivals', y='origin', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['dest_city'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='arrivals', y='dest_city', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [61]:
refugee_df = refugee_df.drop_duplicates(keep='first')

In [62]:
refugee_df[refugee_df.duplicated(keep=False)]

Empty DataFrame
Columns: [year, origin, dest_state, dest_city, arrivals, year_dt]
Index: []

In [ ]:
refugee_df = refugee_df.drop_duplicates(keep='first')
refugee_df.shape

(121231, 6)

### Renaming & Selecting

In [63]:
refugee_df = refugee_df.rename(columns={'dest_state':'state', 'dest_city':'city'})
refugee_df.columns.tolist()

['year', 'origin', 'state', 'city', 'arrivals', 'year_dt']

In [64]:
state_only_df = refugee_df[['state']]
state_series = refugee_df['state']
state_only_df.head(2), type(state_only_df), type(state_series)

(     state
 0  Alabama
 1  Alabama,
 pandas.core.frame.DataFrame,
 pandas.core.series.Series)

In [66]:
refugee_df.columns

Index(['year', 'origin', 'state', 'city', 'arrivals', 'year_dt'], dtype='object')

In [67]:
refugee_df =refugee_df.rename(columns={'dest_state' : 'state', 'dest_city': 'city'})

In [103]:
state_only_df = refugee_df[['state']]
state_series = refugee_df['state']
state_only_df.head(2), type(state_only_df), type(state_series)

(     state
 0  Alabama
 1  Alabama,
 pandas.core.frame.DataFrame,
 pandas.core.series.Series)

❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗

In [105]:
refugee_df[['city', 'state', 'origin']].head(2)

     city    state       origin
0  Mobile  Alabama  Afghanistan
1  Mobile  Alabama  Afghanistan

[[]] double hard braquets is to call the info as data frame. Data frame: spreed sheet

**Try it**
Using `.loc`, select rows where `origin == 'Iraq'` and columns `['year','state','city','arrivals']`. Then compute the mean of `arrivals`.

In [ ]:
# iraq = refugee_df.loc[refugee_df['origin']=='Iraq', ['year','state','city','arrivals']]
# iraq_mean = iraq['arrivals'].mean()
# iraq.head(3), iraq_mean

## Lesson 4: Grouping & Summarizing

In [70]:
by_origin = refugee_df.groupby('origin')
arrivals_sum = by_origin['arrivals'].sum()
arrivals_sum_sorted = arrivals_sum.sort_values(ascending=False)
arrivals_top20 = arrivals_sum_sorted.head(20)
arrivals_top20

origin
Burma              151875
Iraq               127326
Bhutan              85316
Somalia             71120
Cuba                39946
Iran                36683
Dem. Rep. Congo     25493
Russia              15656
Eritrea             14645
Sudan               12636
Ukraine             11727
Burundi             11152
Vietnam             10769
Liberia              9424
Ethiopia             8487
Afghanistan          6751
Laos                 6609
Moldova              4482
Syria                2359
Colombia             1956
Name: arrivals, dtype: int64

In [71]:
by_origin = refugee_df.groupby('origin')

In [72]:
by_origin

In [73]:
arrivals_sum = by_origin['arrivals'].sum()

In [74]:
arrivals_sum

origin
Afghanistan     6751
Albania            3
Algeria            6
Angola            54
Armenia          311
               ...
Venezuela         17
Vietnam        10769
Yemen            112
Zambia             1
Zimbabwe          67
Name: arrivals, Length: 113, dtype: int64

In [75]:
arrivals_sum_sorted = arrivals_sum.sort_values(ascending=False)

In [76]:
arrivals_sum_sorted

origin
Burma                   151875
Iraq                    127326
Bhutan                   85316
Somalia                  71120
Cuba                     39946
                         ...
Philippines                  1
Sweden                       1
United Kingdom               1
United Arab Emirates         1
Zambia                       1
Name: arrivals, Length: 113, dtype: int64

In [77]:
arrivals_top20 = arrivals_sum_sorted.head(20)

In [78]:
arrivals_top20

origin
Burma              151875
Iraq               127326
Bhutan              85316
Somalia             71120
Cuba                39946
Iran                36683
Dem. Rep. Congo     25493
Russia              15656
Eritrea             14645
Sudan               12636
Ukraine             11727
Burundi             11152
Vietnam             10769
Liberia              9424
Ethiopia             8487
Afghanistan          6751
Laos                 6609
Moldova              4482
Syria                2359
Colombia             1956
Name: arrivals, dtype: int64

In [80]:
pd.set_option('display.max_rows', None)

In [82]:
arrivals_sum

origin
Afghanistan                         6751
Albania                                3
Algeria                                6
Angola                                54
Armenia                              311
Azerbaijan                           512
Bangladesh                            10
Belarus                             1565
Benin                                  2
Bhutan                             85316
Bosnia and Herzegovina                36
Bulgaria                               1
Burkina Faso (UVolta)                  7
Burma                             151875
Burundi                            11152
Cambodia                             147
Cameroon                              72
Canada                                 1
Central African Republic            1129
Chad                                 177
China                                477
Colombia                            1956
Congo                               1330
Costa Rica                             2
Croatia                               19
Cuba                               39946
Dem. Rep. Congo                    25493
Djibouti                               5
Ecuador                               12
Egypt                                 88
El Salvador                            6
Equatorial Guinea                     70
Eritrea                            14645
Estonia                               26
Ethiopia                            8487
France                                 1
Gabon                                  8
Gambia                                69
Gaza Strip                             7
Georgia                               95
Germany                                1
Ghana                                 14
Guatemala                              5
Guinea                                38
Guinea - Bissau                        6
Haiti                                 28
Honduras                              25
India                                 18
Indonesia                             25
Iran                               36683
Iraq                              127326
Israel                                 3
Ivory Coast                          229
Jamaica                                1
Jordan                                39
Kazakhstan                           550
Kenya                                 60
Korea, North                         191
Kuwait                               109
Kyrgyzstan                           285
Laos                                6609
Latvia                                66
Lebanon                               11
Liberia                             9424
Libya                                  8
Lithuania                             15
Macedonia                              1
Madagascar (Malagasy Republic)         4
Malaysia                               6
Mali                                  12
Mauritania                           276
Moldova                             4482
Montenegro                             2
Morocco                                7
Namibia                                5
Nepal                                183
Netherlands                            2
Niger                                  5
Nigeria                              136
Pakistan                            1210
Palestine                           1817
Philippines                            1
Republic of South Sudan              181
Russia                             15656
Rwanda                              1516
Saudi Arabia                           7
Senegal                               20
Serbia                                31
Sierra Leone                        1364
Somalia                            71120
South Africa                           3
Sri Lanka (Ceylon)                   536
Sudan                              12636
Sweden                                 1
Syria                               2359
Tajikistan                            21
Tanzania                               4
Thailand                              23
Tibet                                 31
Togo                                 401
Tunisia                               12
Turkey                                11
Turkmenistan                          36
Uganda                               267
Ukraine                            11727
United Arab Emirates                   1
United Kingdom                         1
Uzbekistan                          1800
Venezuela                             17
Vietnam                            10769
Yemen                                112
Zambia                                 1
Zimbabwe                              67
Name: arrivals, dtype: int64

In [83]:
ref_sum_df = arrivals_top20.to_frame().reset_index()
ref_sum_df.head()

    origin  arrivals
0    Burma    151875
1     Iraq    127326
2   Bhutan     85316
3  Somalia     71120
4     Cuba     39946

In [84]:
ref_sum_df = arrivals_top20.to_frame()

**Try it**
Compute the top 10 states by total arrivals and save as `state_sum_df`.

In [ ]:
# state_sum_df = (refugee_df.groupby('state')['arrivals']
#                                .sum()
#                                .sort_values(ascending=False)
#                                .head(10)
#                                .to_frame()
#                                .reset_index())
# state_sum_df

## Lesson 5: Quick Visuals with pandas `.plot()`

❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗

In [87]:
ax = ref_sum_df.plot(kind='barh', x='origin', y='arrivals', figsize=(12,6),
                      title='Total refugee arrivals by country of origin (Top 20)')

KeyError: 'origin'

**Try it**
Make a line chart of total arrivals by year.

In [ ]:
# total_by_year = refugee_df.groupby('year')['arrivals'].sum()
# ax = total_by_year.plot(kind='line', figsize=(10,5), title='Total arrivals by year')

## Lesson 6: Interactive Charts with Plotly Express

In [88]:
# !pip -q install plotly
import plotly.express as px

### Bar chart (interactive)

In [ ]:
origin_sum = (refugee_df.groupby('origin')['arrivals']
               .sum().sort_values(ascending=False).head(15).reset_index())
fig = px.bar(origin_sum, x='origin', y='arrivals',
             title='Total refugee arrivals by origin (Top 15)')
fig.show()

In [89]:
origin_sum = (refugee_df.groupby('origin')['arrivals']
               .sum().sort_values(ascending=False).head(15).reset_index())

In [91]:
fig = px.bar(origin_sum, x='origin', y='arrivals',
             title='Total refugee arrivals by origin (Top 15)')

In [92]:
fig.show()

In [90]:
origin_sum

             origin  arrivals
0             Burma    151875
1              Iraq    127326
2            Bhutan     85316
3           Somalia     71120
4              Cuba     39946
5              Iran     36683
6   Dem. Rep. Congo     25493
7            Russia     15656
8           Eritrea     14645
9             Sudan     12636
10          Ukraine     11727
11          Burundi     11152
12          Vietnam     10769
13          Liberia      9424
14         Ethiopia      8487

### Line chart (interactive)

In [ ]:
total_by_year = refugee_df.groupby('year')['arrivals'].sum().reset_index()
fig = px.line(total_by_year, x='year', y='arrivals', markers=True,
              title='Total refugee arrivals by year (2005–2015)')
fig.show()

In [93]:
total_by_year = refugee_df.groupby('year')['arrivals'].sum().reset_index()

In [94]:
fig = px.line(total_by_year, x='year', y='arrivals', markers=True,
              title='Total refugee arrivals by year (2005–2015)')

In [95]:
fig.show()

### Scatter with faceting

In [ ]:
focus = refugee_df[refugee_df['origin'].isin(['Iraq','Somalia','Bhutan','Burma','Iran'])]
by_pair = focus.groupby(['origin','year'])['arrivals'].sum().reset_index()
fig = px.scatter(by_pair, x='year', y='arrivals', color='origin',
                 facet_col='origin', facet_col_wrap=3,
                 title='Yearly arrivals for selected origins')
fig.show()

In [96]:
focus = refugee_df[refugee_df['origin'].isin(['Iraq','Somalia','Bhutan','Burma','Iran'])]
by_pair = focus.groupby(['origin','year'])['arrivals'].sum().reset_index()

In [97]:
fig = px.scatter(by_pair, x='year', y='arrivals', color='origin',
                 facet_col='origin', facet_col_wrap=3,
                 title='Yearly arrivals for selected origins')

In [98]:
fig.show()

## Save Artifacts (CSV)

In [ ]:
refugee_df.to_csv('refugee_clean.csv', index=False)
try:
    from google.colab import files
    files.download('refugee_clean.csv')
except Exception:
    print('File saved to working directory.')

---
End of Workbook.